apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus-3
  name: girus-3
spec:
  containers:
  - image: nginx
    name: girus-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
